import Head from 'next/head'
import dynamic from 'next/dynamic'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Online Utilities - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="flex flex-col items-center min-h-screen w-full flex-1 px-20 text-center">
        <h1 className='text-3xl text-white font-bold'>Homepage</h1>
      </main>
    </div>
  )
}
