import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const DynamicJSONValidate = dynamic(
  () => import('../components/inputPanel/InputPanel'),
  { ssr: false }
)

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Online Utilities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="flex flex-col items-center min-h-screen w-full flex-1 px-20 text-center">
        <DynamicJSONValidate/>
      </main>
    </div>
  )
}
